### ISSUE TITLE
Feedback on number bases and search algorithms

### ISSUE THREAD

**Issue by Anisha7** [sprajjwal/CS-1.3-Core-Data-Structures#1]
**Number bases**
Great work on your number base methods! Try optimizing your code by avoiding usage of pow or **.

**Binary search**
Great job on attempting the binary search algorithm. It looks like your algorithms (both recursive and iterative) are failing on one edge case. It seems to never check the last index. Try printing what indices the midpoint function is getting to for the test case that is failing, and see how you could modify your midpoint or other parameters to cover all indices.

**Comment by sprajjwal** [comment]
My search was failing because I had a type in my test 🤦‍♂ Fixed it and now it should be passing every case.
